<a href="https://colab.research.google.com/github/accelleratorcloud/PublicNotebooks/blob/main/VariousExperements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import platform
import sys

In [ ]:
thing = open("listdoc.txt",'r')

In [ ]:
type(thing)

_io.TextIOWrapper

In [ ]:
help(_io.TextIOWrapper)

NameError: name '_io' is not defined

In [ ]:
dir(_io)

NameError: name '_io' is not defined

In [ ]:
thing2 = open("listdoc.txt",'rb')

In [ ]:
type(thing2)

_io.BufferedReader

In [ ]:
thing[1]

TypeError: '_io.TextIOWrapper' object is not subscriptable

In [ ]:
thing.fileno()

56

In [ ]:
thing.buffer

<_io.BufferedReader name='listdoc.txt'>

In [ ]:
thing2

<_io.BufferedReader name='listdoc.txt'>

In [ ]:
mydict = dict(a=1,b=9,c=7,d=15,e=12,f=4)
mydict

{'a': 1, 'b': 9, 'c': 7, 'd': 15, 'e': 12, 'f': 4}

In [ ]:
sorted(mydict.items(),key=lambda x:x[1],reverse=True)

[('d', 15), ('e', 12), ('b', 9), ('c', 7), ('f', 4), ('a', 1)]

In [ ]:
sorted(mydict.items(),key=lambda x:x[0])

[('a', 1), ('b', 9), ('c', 7), ('d', 15), ('e', 12), ('f', 4), ('z', 999)]

In [ ]:
mydict.setdefault('z',999)

999

In [ ]:
mydict

{'a': 1, 'b': 9, 'c': 7, 'd': 15, 'e': 12, 'f': 4, 'z': 999}

In [ ]:
anotherdict = {"a":1,2:3,(1,2):(2,3), 2.5:3.7,  [1,2]:[2,3] }
anotherdict

TypeError: unhashable type: 'list'

In [ ]:
mylist = "zulu alpha charlie epsilon delta hotel".split()
mylist

['zulu', 'alpha', 'charlie', 'epsilon', 'delta', 'hotel']

In [ ]:
mylist.sort()

In [ ]:
mylist

['alpha', 'charlie', 'delta', 'epsilon', 'hotel', 'zulu']

In [ ]:
mylist.sort(reverse=True)

In [ ]:
mylist

['zulu', 'hotel', 'epsilon', 'delta', 'charlie', 'alpha']

In [ ]:
mylist.sort(key=lambda x:x)

In [ ]:
mylist

['alpha', 'charlie', 'delta', 'epsilon', 'hotel', 'zulu']

In [ ]:
help(mylist.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Sort the list in ascending order and return None.
    
    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).
    
    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.
    
    The reverse flag can be set to sort in descending order.



In [ ]:
dwight_sales = [192,156,222,224,226,176,193,244,238,156,249,222,173,240,230,183,174,177,214,184]

In [ ]:
myfilter = filter(lambda number:number%2==1, dwight_sales)

In [ ]:
myfilter

In [ ]:
sorted_sales = sorted(dwight_sales, key=lambda x:x)
sorted_sales

[156,
 156,
 173,
 174,
 176,
 177,
 183,
 184,
 192,
 193,
 214,
 222,
 222,
 224,
 226,
 230,
 238,
 240,
 244,
 249]

In [ ]:
list(myfilter)

[193, 249, 173, 183, 177]

In [ ]:
from functools import reduce

numbers = [2, 3, 4, 5]
product = reduce(lambda x, y: x * y, numbers)

print(product)

120


In [ ]:
product = reduce(lambda x,y: x*x , numbers)

In [ ]:
product

256

In [ ]:
product = reduce(lambda x,y,z: (x,y,z) , numbers)
product

TypeError: <lambda>() missing 1 required positional argument: 'z'

In [ ]:
import sys
import platform
import os

In [ ]:
sys.path

['/media/rob/PCI_NVME/JupyterNotebooks',
 '/home/rob/anaconda3/lib/python39.zip',
 '/home/rob/anaconda3/lib/python3.9',
 '/home/rob/anaconda3/lib/python3.9/lib-dynload',
 '',
 '/home/rob/anaconda3/lib/python3.9/site-packages',
 '/home/rob/anaconda3/lib/python3.9/site-packages/IPython/extensions',
 '/home/rob/.ipython']

In [ ]:
################################################################################
### reduce() sequence to a single item
################################################################################

_initial_missing = object()

def myreduce(function, sequence, initial=_initial_missing):
    """
    reduce(function, sequence[, initial]) -> value

    Apply a function of two arguments cumulatively to the items of a sequence,
    from left to right, so as to reduce the sequence to a single value.
    For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
    ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
    of the sequence in the calculation, and serves as a default when the
    sequence is empty.
    """

    it = iter(sequence)

    if initial is _initial_missing:
        try:
            value = next(it)
        except StopIteration:
            raise TypeError("reduce() of empty sequence with no initial value") from None
    else:
        value = initial

    for element in it:
        value = function(value, element)

    return value

In [ ]:
myreduce(lambda x, y: x * y, numbers)

120

In [ ]:
help(iter)

Help on built-in function iter in module builtins:

iter(...)
    iter(iterable) -> iterator
    iter(callable, sentinel) -> iterator
    
    Get an iterator from an object.  In the first form, the argument must
    supply its own iterator, or be a sequence.
    In the second form, the callable is called until it returns the sentinel.



In [ ]:
number1 = 987654321987654321987654321

In [ ]:
number1,-number1

(987654321987654321987654321, -987654321987654321987654321)

In [ ]:
number2 = int("-987654321987654321987654321")
number2

-987654321987654321987654321

In [ ]:
float1 = 987654321987654321987654321.
float1

9.876543219876543e+26

In [ ]:
import decimal

In [ ]:
import numpy

In [ ]:
decimal1 = decimal.Decimal(987654321987654321987654321.)

In [ ]:
decimal1

Decimal('987654321987654258182324224')

In [ ]:
decimal2 = decimal.Decimal(9.87)
decimal2

Decimal('9.8699999999999992184029906638897955417633056640625')

In [ ]:
float2 = 9.87654321987654321987654321
float2

9.876543219876543

In [ ]:
datatypes = [
    ["bool", "int","float","str","bytes"],
    ["list","tuple","set","dictionary","array.array","numpy.ndarray","class"]
    ]

In [ ]:
bool(0), bool(1)

(False, True)

In [ ]:
False or True,  True and True,  True and False

(True, True, False)

In [ ]:
datatypes[1]

['list', 'tuple', 'set', 'dictionary']

In [ ]:
mybytes = b"abc"
mybytes, type(mybytes)

(b'abc', bytes)

In [ ]:
# Creating a bytes object from a list of integers
byte_data = bytes([72, 101, 108, 108, 111])  # b'Hello'

# Creating a bytes object from a string
encoded_bytes = bytes("Hello, world!", encoding='utf-8')

# Creating a bytes object from size
null_bytes = bytes(5)

# Converting bytes back to a string
decoded_string = encoded_bytes.decode('utf-8')  # 'Hello, world!'

# Getting hexadecimal representation
hex_representation = encoded_bytes.hex()  # '48656c6c6f2c20776f726c6421'

In [ ]:
hex_representation

'48656c6c6f2c20776f726c6421'

In [ ]:
byte_data

b'Hello'

In [ ]:
import array
# Create an array of signed integers (type 'i')
lame_array = array.array('i', [1, 2, 3, 4, 5])
lame_array

array('i', [1, 2, 3, 4, 5])

In [ ]:
import numpy as np

# Create a 2-dimensional array with explicit data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(data)

numpy.ndarray

In [ ]:
data[0]

array([1, 2, 3], dtype=int32)

In [ ]:
data[0,:]

array([1, 2, 3], dtype=int32)

In [ ]:
data[:,0]

array([1, 4, 7], dtype=int32)

In [ ]:
squarelist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Generate a set of uppercase and lowercase Greek letters along with their Unicode code points
greek_letters = {
    'Uppercase': {chr(code): code for code in range(0x0391, 0x03AA)},
    'Lowercase': {chr(code): code for code in range(0x03B1, 0x03CA)}
}

# Display the Greek letters and their Unicode code points
for letter_type, letters in greek_letters.items():
    print(f"{letter_type} Greek Letters:")
    for letter, code in letters.items():
        print(f"{letter}: U+{code:04X}")


Uppercase Greek Letters:
Α: U+0391
Β: U+0392
Γ: U+0393
Δ: U+0394
Ε: U+0395
Ζ: U+0396
Η: U+0397
Θ: U+0398
Ι: U+0399
Κ: U+039A
Λ: U+039B
Μ: U+039C
Ν: U+039D
Ξ: U+039E
Ο: U+039F
Π: U+03A0
Ρ: U+03A1
΢: U+03A2
Σ: U+03A3
Τ: U+03A4
Υ: U+03A5
Φ: U+03A6
Χ: U+03A7
Ψ: U+03A8
Ω: U+03A9
Lowercase Greek Letters:
α: U+03B1
β: U+03B2
γ: U+03B3
δ: U+03B4
ε: U+03B5
ζ: U+03B6
η: U+03B7
θ: U+03B8
ι: U+03B9
κ: U+03BA
λ: U+03BB
μ: U+03BC
ν: U+03BD
ξ: U+03BE
ο: U+03BF
π: U+03C0
ρ: U+03C1
ς: U+03C2
σ: U+03C3
τ: U+03C4
υ: U+03C5
φ: U+03C6
χ: U+03C7
ψ: U+03C8
ω: U+03C9


In [ ]:
λ = [1,2,3]
λ

[1, 2, 3]

In [ ]:
import numpy as np

# Example vectors as columns of a matrix
vectors_matrix = np.array([[0, -27, 3],
                           [2, 5, 1],
                           [5, -37, 8]])


# The rank of a matrix is the maximum number of linearly independent rows or columns in the matrix. In other words, it represents the dimension of the vector space spanned by the rows or columns of the matrix.

# For a matrix with 'm' rows and 'n' columns:

# The rank of the matrix is at most min(m, n).
# If the rank is less than min(m, n), it means that there are linearly dependent rows or columns in the matrix.

rank = np.linalg.matrix_rank(vectors_matrix)
print("rank of matrix:",rank)

# Check if the vectors are linearly independent
num_vectors = vectors_matrix.shape[1]
print("number of vectors:", num_vectors)
are_linearly_independent = rank == num_vectors

print("Vectors are linearly independent:", are_linearly_independent)

A = np.array([
                           [0,  3],
                           [2,  1],
                           [5,  8]
                        ])
b = np.array([
                           [-27],
                           [5],
                           [-37]
                        ])

# Find the least-squares solution
x, residuals, rank, s = np.linalg.lstsq(A, b)
print("Least-squares solution x:", x.T)

rank of matrix: 2
number of vectors: 3
Vectors are linearly independent: False
Least-squares solution x: [[ 7. -9.]]


/tmp/ipykernel_16927/1124348610.py:31: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(A, b)


![image.png](attachment:28806b54-33f6-4f95-9c84-e5153e42a1ad.png)

In [ ]:
import numpy as np

# Example vectors as columns of a matrix
vectors_matrix = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Example target vector
target_vector = np.array([10, 11, 12])

# Solve the linear system to find the coefficients
coefficients = np.linalg.solve(vectors_matrix, target_vector)

print("Coefficients:", coefficients)

Coefficients: [-25.33333333  41.66666667 -16.        ]


In [ ]:
import numpy as np

# Create a NumPy array (you can replace this with your own array)
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the NumPy array to a file
np.save("numpy_array.npy", numpy_array)

In [ ]:
vectors_matrix + target_vector.T

array([[11, 13, 15],
       [14, 16, 18],
       [17, 19, 21]])

In [ ]:
randomarray = np.random.rand( 4,2 )
randomarray

array([[0.25555646, 0.20136565],
       [0.23762723, 0.08473555],
       [0.01583758, 0.51619921],
       [0.52831854, 0.05486811]])

order{‘C’, ‘F’, ‘A’, or ‘K’}, optional
Overrides the memory layout of the result. ‘C’ means C-order, ‘F’ means F-order, ‘A’ means ‘F’ if a is Fortran contiguous, ‘C’ otherwise. ‘K’ means match the layout of a as closely as possible.

shapeint or sequence of ints, optional.
Overrides the shape of the result. If order=’K’ and the number of dimensions is unchanged, will try to keep order, otherwise, order=’C’ is implied.

In [ ]:
np.full_like(randomarray, 7, order='K')

array([[7., 7.],
       [7., 7.],
       [7., 7.],
       [7., 7.]])

In [ ]:
myones = np.ones( (3,4), dtype=np.int8)
myones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
np.random.random_sample(myones.shape)

array([[0.49892222, 0.80696207, 0.23269805, 0.55283567],
       [0.80789394, 0.87494092, 0.91216878, 0.55436462],
       [0.51167018, 0.5765158 , 0.59112791, 0.86489824]])

In [ ]:
randints = np.random.randint
randints

array([2, 0])

In [ ]:
np.random.random_integers(1,6,myones.shape)

/tmp/ipykernel_16927/2734284539.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  np.random.random_integers(1,6,myones.shape)


array([[4, 4, 2, 4],
       [6, 3, 3, 6],
       [1, 6, 4, 5]])

In [ ]:
nestedlist = [[1,2],
              [3,4]]
nestedlist*2

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [ ]:
onedimensional = np.array([1,2,3])
oneDcopy = onedimensional[:]
oneDcopy

array([1, 2, 3])

In [ ]:
twodimensional = np.array([[1,2,3],[4,5,6],[7,8,9]])
twoDcopy = twodimensional[:,:]
twoDcopy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
anyDcopy = twodimensional.copy()
anyDcopy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
thefifthdimension = np.ones( (2,2,2,2,2), dtype=np.int8)
thefifthdimension

array([[[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]],



       [[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]]], dtype=int8)

In [ ]:
randintcube = np.random.randint(0,9,(3,3,3))
randintcube

array([[[2, 4, 6],
        [2, 2, 1],
        [1, 7, 6]],

       [[2, 2, 5],
        [0, 7, 1],
        [2, 6, 8]],

       [[0, 5, 1],
        [6, 8, 8],
        [8, 5, 1]]])

In [ ]:
np.random.randn(2,3,4)

array([[[-1.82981805,  0.01809017,  1.04756723,  0.78152373],
        [ 0.15477715,  0.74589502,  1.41390433,  0.77957715],
        [-1.18824739,  1.60307571, -1.09185013,  0.25501848]],

       [[-1.07613292,  0.11863311,  1.73586904,  0.2177209 ],
        [ 1.22837244,  1.37926625,  0.97919434,  0.40923753],
        [-0.34623885, -0.36381963,  1.0344624 ,  0.53166799]]])

In [ ]:
import numpy as np

# Create two NumPy arrays (you can replace these with your own arrays)
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.0000001, 2.0000002, 3.0000003])

# Set the tolerance (absolute or relative difference) for the comparison
tolerance = 1e-6

# Compare the arrays with numpy.allclose()
are_equal = np.allclose(array1, array2, rtol=tolerance, atol=tolerance)

print("Are the arrays equal within the tolerance?", are_equal)

Are the arrays equal within the tolerance? True
